global:
  environment: production
  revisionHistoryLimit: 15
  vault_token: aHZzLkNBRVNJT1hOU21PZ3ZuRXMzT0xFbnNxbERac3Q2NnBsTWpPNm83ZE1pcVJnamZrYUdoNEtIR2gyY3k1a2ExaGtVRlZxZWsxUmQxRmxVV1ZSV0hOSlJIcDZiMm8=
  dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogIlpDNXdZWE5vYTI5Mk9paGtOalJZZGxjbENnPT0iCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQo=
  proxy_pass_Name: backend
  proxy_pass_Port: 8080

backend:
  replicaCount: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 20%
  containersName: backend
  containerPort: 8080
  servicePort: 8080
  updatePolicy:
    updateMode: "Recreate"
  resourcePolicy:
    containerName: "*"
    minAllowed:
      cpu: 0m
      memory: 0Mi
    maxAllowed:
      cpu: 1
      memory: 500Mi
  image:
    repository: gitlab.praktikum-services.ru:5050/std-009-057/sausage-store/sausage-backend
    tag: latest
    imagePullPolicy: Always
  env:
    - name: VAULT_URL
      value: 84.201.130.88

backend-report:
  replicaCount: 1
  containersName: backend-report
  containerPort: 8080
  servicePort: 8080
  image: 
    repository: gitlab.praktikum-services.ru:5050/std-009-057/sausage-store/sausage-backend-report
    tag: latest
    imagePullPolicy: Always
  env:
    - name: VAULT_URL
      value: 84.201.130.88
  request:
    cpu: 100m
  limits:
    cpu: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 5
    averageUtilization: 75

frontend:
  replicaCount: 1
  containerPort: 8080
  servicePort: 8080
  containersName: frontend
  fqdn: std-009-067.k8s.praktikum-services.tech
  image:
    repository: gitlab.praktikum-services.ru:5050/std-009-057/sausage-store/sausage-frontend
    tag: latest
    imagePullPolicy: Always
  ingress:
    tls:
      hosts: "std-009-067.k8s.praktikum-services.tech"
    rules: 
      host: "std-009-067.k8s.praktikum-services.tech"
    rootpath:
      port:
        number: 8080
