all: # Все серверы в нашем inventory, all - обязателен
  children: # Дочерние группы для all
    backend: # Группа хостов с именем backend
      hosts:
        10.129.0.8:
    frontend:
      hosts:
        sausage-frontend.example.com:
          10.129.0.8: