---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  revisionHistoryLimit: 15
  replicas: 1
  # Стратегия развёртывания. Recreate — удалит сначала все старые поды
  # Есть и более гибкая стратегии, например, RollingUpdate, которая будет обновлять поды порциями
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 80%
      maxSurge: 20%
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gitlab.praktikum-services.ru:5050/std-009-057/sausage-store/sausage-backend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: VAULT_URL
              value: 84.201.130.88
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: vault_token
          ports:
            - name: backend
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 6
      imagePullSecrets:
        - name: docker-config-secret
