# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: aHZzLkNBRVNJT1hOU21PZ3ZuRXMzT0xFbnNxbERac3Q2NnBsTWpPNm83ZE1pcVJnamZrYUdoNEtIR2gyY3k1a2ExaGtVRlZxZWsxUmQxRmxVV1ZSV0hOSlJIcDZiMm8=
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIlpYSmhhMmh0WlhSNmVXRnViM1k2TlZrNWNESnlSM05RUVcxS>
type: kubernetes.io/dockerconfigjson