# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: aHZzLkNBRVNJREUxTW55dG56Qml0YVBTcGxFYnpXWU9nZnVWSm15NWl4eG9LU1ZNNmtPbkdoNEtIR2gyY3k1U1NVOXVPRVpyZDFKck4xVmlWRk5FUVVOYWMwaHJUaz>
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIlpYSmhhMmh0WlhSNmVXRnViM1k2TlZrNWNESnlSM05RUVcxS>
type: kubernetes.io/dockerconfigjson