---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  # Стратегия развёртывания. Recreate — удалит сначала все старые Pod'ы
  # Есть и более гибкая стратегии, например, RollingUpdate, которая будет обновлять Pod'ы порциями
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gitlab.praktikum-services.ru:5050/std-009-057/sausage-store/sausage-frontend:latest
          imagePullPolicy: Always
          ports:
            - name: frontend
              containerPort: 8080
          volumeMounts:
          - name: nginx-front-conf
            mountPath: /etc/nginx/conf.d/
      volumes:
      - name: nginx-front-conf
        configMap:
          name: nginx-front-conf